"""Tests for response validator."""

import pytest
from unittest.mock import AsyncMock, MagicMock

from national_treasure.services.browser.validator import (
    ResponseValidator,
    validate_response,
    BLOCK_PATTERNS,
    CAPTCHA_PATTERNS,
    RATE_LIMIT_PATTERNS,
)


class MockResponse:
    """Mock Playwright Response."""

    def __init__(self, status: int = 200, headers: dict = None):
        self.status = status
        self.headers = headers or {}


class MockPage:
    """Mock Playwright Page."""

    def __init__(self, content: str = "", text_content: str = ""):
        self._content = content
        self._text_content = text_content

    async def content(self):
        return self._content

    async def evaluate(self, script):
        return self._text_content


class TestBlockPatterns:
    """Tests for block pattern detection."""

    def test_cloudflare_patterns(self):
        """Should have Cloudflare detection patterns."""
        cf_pattern = next(
            p for p in BLOCK_PATTERNS if p.service.value == "cloudflare"
        )
        assert "just a moment" in cf_pattern.patterns
        assert "checking your browser" in cf_pattern.patterns

    def test_cloudfront_patterns(self):
        """Should have CloudFront detection patterns."""
        cf_pattern = next(
            p for p in BLOCK_PATTERNS if p.service.value == "cloudfront"
        )
        assert "generated by cloudfront" in cf_pattern.patterns


class TestCaptchaPatterns:
    """Tests for CAPTCHA detection."""

    def test_has_recaptcha(self):
        """Should detect reCAPTCHA."""
        assert "recaptcha" in CAPTCHA_PATTERNS

    def test_has_hcaptcha(self):
        """Should detect hCaptcha."""
        assert "hcaptcha" in CAPTCHA_PATTERNS

    def test_has_turnstile(self):
        """Should detect Cloudflare Turnstile."""
        assert "cf-turnstile" in CAPTCHA_PATTERNS


class TestResponseValidator:
    """Tests for ResponseValidator."""

    @pytest.mark.asyncio
    async def test_valid_response(self):
        """Should accept valid response."""
        validator = ResponseValidator(min_content_length=10)
        response = MockResponse(status=200)
        page = MockPage(
            content="<html><body>Long enough content here</body></html>",
            text_content="Long enough content here",
        )

        result = await validator.validate(response, page)
        assert result.blocked is False

    @pytest.mark.asyncio
    async def test_none_response(self):
        """Should detect navigation failure."""
        validator = ResponseValidator()
        page = MockPage()

        result = await validator.validate(None, page)
        assert result.blocked is True
        assert result.reason == "navigation_failed"

    @pytest.mark.asyncio
    async def test_403_response(self):
        """Should detect 403 forbidden."""
        validator = ResponseValidator()
        response = MockResponse(status=403)
        page = MockPage(content="Forbidden")

        result = await validator.validate(response, page)
        assert result.blocked is True
        assert "403" in result.reason

    @pytest.mark.asyncio
    async def test_cloudflare_block(self):
        """Should detect Cloudflare block."""
        validator = ResponseValidator(min_content_length=10)
        response = MockResponse(status=200)
        page = MockPage(
            content="<html><body>Just a moment... Checking your browser</body></html>",
            text_content="Just a moment... Checking your browser",
        )

        result = await validator.validate(response, page)
        assert result.blocked is True
        assert "cloudflare" in result.reason.lower()

    @pytest.mark.asyncio
    async def test_captcha_detection(self):
        """Should detect CAPTCHA."""
        validator = ResponseValidator(min_content_length=10)
        response = MockResponse(status=200)
        page = MockPage(
            content='<html><body><div class="g-recaptcha"></div></body></html>',
            text_content="Please complete the captcha",
        )

        result = await validator.validate(response, page)
        assert result.blocked is True
        assert result.reason == "captcha"

    @pytest.mark.asyncio
    async def test_rate_limit_detection(self):
        """Should detect rate limiting."""
        validator = ResponseValidator(min_content_length=10)
        response = MockResponse(status=200)
        page = MockPage(
            content="<html><body>Too many requests. Please slow down.</body></html>",
            text_content="Too many requests. Please slow down.",
        )

        result = await validator.validate(response, page)
        assert result.blocked is True
        assert result.reason == "rate_limited"

    @pytest.mark.asyncio
    async def test_custom_block_pattern(self):
        """Should detect custom block patterns."""
        validator = ResponseValidator(
            min_content_length=10,
            custom_block_patterns=["site maintenance"],
        )
        response = MockResponse(status=200)
        page = MockPage(
            content="<html><body>Site maintenance in progress</body></html>",
            text_content="Site maintenance in progress",
        )

        result = await validator.validate(response, page)
        assert result.blocked is True
        assert result.reason == "custom_block"

    @pytest.mark.asyncio
    async def test_custom_success_pattern(self):
        """Should accept custom success patterns."""
        validator = ResponseValidator(
            min_content_length=1000,  # High threshold
            custom_success_patterns=["successfully loaded"],
        )
        response = MockResponse(status=200)
        page = MockPage(
            content="<html><body>Page successfully loaded</body></html>",
            text_content="Page successfully loaded",
        )

        result = await validator.validate(response, page)
        assert result.blocked is False

    @pytest.mark.asyncio
    async def test_cloudflare_header_detection(self):
        """Should detect Cloudflare from headers."""
        validator = ResponseValidator()
        response = MockResponse(status=403, headers={"cf-ray": "abc123"})
        page = MockPage(content="Access denied")

        result = await validator.validate(response, page)
        assert result.blocked is True


class TestValidateResponseFunction:
    """Tests for convenience function."""

    @pytest.mark.asyncio
    async def test_validate_response_convenience(self):
        """Should use default validator."""
        response = MockResponse(status=200)
        page = MockPage(
            content="<html><body>Valid content here</body></html>",
            text_content="Valid content here",
        )

        result = await validate_response(response, page, min_content_length=10)
        assert result.blocked is False
